version: "2"
run:
  issues-exit-code: 1
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 4095
  max-same-issues: 1023
  #new: true
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
